(in-package :r-html)

(defun recycling-information-html ()
  (my-html
   `(:div
     ((:class "info-page-contents"))
     (:h1 "Recycling Information")
     (:div
      ((:class "Recycling-Facts"))
      (:h2 "Recycling Facts")
      (:div
       ((:class "Recycling-Facts-list"))
       (:div (:h3 "254") (:h4 "Million tons"))
       (:p "Amount of trash generated by Americans every year, about
       12% of the world's yearly trash total of about 2.05 billion tons.")
       (:div (:h3 "12") (:h4 "Feet"))
       (:p "The height of a wall from Los Angeles to New York
        City (2790 miles) that could be built from one year of tossed
        office paper.")
       (:div (:h3 "300") (:h4 "Laps"))
       (:p "How many laps around the equator that could be made in
        paper and plastic cups, forks, and spoons that are disposed of
        annually.")
       (:div (:h3 "2050"))
       (:p "The year in which scientists estimate that plastic litter
        in the ocean outweighs the amount of fish.")))
     (:div
      ((:class "recycling-chicago"))
      (:h2 "Recycling in Chicago")
      (:div
       ((:class "recycling-chicago-information"))
       (:figure
        (:img ((:src "resources/images/information/ChicagoRecyclingBinZones.png")))
        (:figcaption
         "Source from "
         (:a ((:href "https://projects.bettergov.org/2018/recycling-chicago/"))
             "https://projects.bettergov.org/2018/recycling-chicago/")))
       (:ul
        ((:class "recycling-chicago-info-points"))
        (:li "3% of all reyclable items are marked as contaminated
        within the city of Chicago")
        (:li "Waste Management operates approximately 50% of the city’s
        trash, yet tags bins as contaminated over 20 times more
        often than others.")
        (:li "Lakeshore is a single stream recycling company that
        operates around 20% of all recycling in Chicago.")
        (:li "They are a relatively sustainable company, but one
        potential inefficiency is that they do all their recycling by hand.")
        (:li "Less than 9% of Chicago’s residential waste is recycled,
             this is the worst rate in the entire United States."))))
     (:div
      ((:class "info-resources"))
      (:h2 "Sources")
      (:ul
       (:li
        (:a
         ((:href "https://news.wttw.com/2017/06/26/where-does-chicago-s-garbage-go"))
         "WTTW News - 'Where Does Chicago's Garbage Go?' by Elizabeth Brackett"))
       (:li
        (:a
         ((:href "https://projects.bettergov.org/2018/recycling-chicago/"))
         "Better Government Association - 'Recycling in Chicago' by Madison Hopkins"))
       (:li
        (:a
         ((:href "https://www.nbcchicago.com/investigations/chicago-recycling-not-being-recycled-497049481.html"))
         "NBC Chicago - 'A Lot of Chicago Recycling Isn’t Getting Recycled: Report'"))
       (:li
        (:a
         ((:href "https://news.wttw.com/2018/11/19/study-chicago-not-only-city-illinois-struggling-boost-recycling-rate"))
         "WTTW News - 'Study: Chicago Not Only City in Illinois
         Struggling to Boost Recycling Rate' by Alex Ruppenthal"))
       (:li
        (:a
         ((:href "https://news.wttw.com/2017/06/27/chicago-recycling-numbers"))
         "WTTW News - 'Chicago Recycling, By the Numbers' by Alex Ruppenthal"))
       (:li
        (:a
         ((:href "https://depauliaonline.com/37248/news/chicago-ranked-worst-major-american-city-for-recycling/"))
         "The DePaulia - 'Chicago ranked worst major American city for
         recycling' by Ella Lee"))))
     (:div
      ((:class "TBD"))
      (:h2 "To be Added")
      (:ul
       (:li "How to recycle and/or instructions to recycle")
       (:li "Incentives to recycle"))
      )

     ))  )
