(in-package :r-html)

(defun recycling-information-html ()
  (my-html
   `(:div
     ((:class "info-page-contents"))
     (:h1 "Recycling Information")
     (:div
      ((:class "Recycling-Facts"))
      (:h2 "Recycling Facts")
      (:div
       ((:class "Recycling-Facts-list"))
       (:div (:h3 "254") (:h4 "Million tons"))
       (:p "Amount of trash generated by Americans every year, about
       12% of the world's yearly trash total of about 2.05 billion tons.")
       (:div (:h3 "12") (:h4 "Feet"))
       (:p "The height of a wall from Los Angeles to New York
        City (2790 miles) that could be built from one year of tossed
        office paper.")
       (:div (:h3 "300") (:h4 "Laps"))
       (:p "How many laps around the equator that could be made in
        paper and plastic cups, forks, and spoons that are disposed of
        annually.")
       (:div (:h3 "2050"))
       (:p "The year in which scientists estimate that plastic litter
        in the ocean outweighs the amount of fish.")))
     (:div
      ((:class "recycling-chicago"))
      (:h2 "Recycling in Chicago")
      (:div
       ((:class "recycling-chicago-information"))
       (:figure
        (:img ((:src "resources/pages/information/ChicagoRecyclingBinZones.png")))
        (:figcaption
         "Source from "
         (:a ((:href "https://projects.bettergov.org/2018/recycling-chicago/"))
             "https://projects.bettergov.org/2018/recycling-chicago/")))
       (:ul
        ((:class "recycling-chicago-info-points"))
        (:li "3% of all reyclable items are marked as contaminated
        within the city of Chicago")
        (:li "Waste Management operates approximately 50% of the city’s
        trash, yet tags bins as contaminated over 20 times more
        often than others.")
        (:li "Lakeshore is a single stream recycling company that
        operates around 20% of all recycling in Chicago.")
        (:li "They are a relatively sustainable company, but one
        potential inefficiency is that they do all their recycling by hand.")
        (:li "Less than 9% of Chicago’s residential waste is recycled,
             this is the worst rate in the entire United States."))))
     (:div
      ((:class "How-to-recycle-classes"))
      (:h2 "What to Watch Out For When Recycling Each Class")
      (:div
       ((:class "Recycling-each-class"))
       (:div
        ((:class "recycling-plastics-process"))
        (:h2 "Plastics")
        ,(plastic-recycling-process))
       (:div
        ((:class "recycling-metals-process"))
        (:h2 "Metals")
        ,(metals-recycling-process))
       (:div
        ((:class "recycling-paper-process"))
        (:h2 "Paper or Cardboard")
        ,(paper-recycling-process))
       (:div
        ((:class "recycling-glass-process"))
        (:h2 "Glass")
        ,(glass-recycling-process))
       (:div
        ((:class "recycling-electronics-process"))
        (:h2 "Electronics")
        ,(electronics-recycling-process))
       (:div
        ((:class "recycling-bulbs-process"))
        (:h2 "Bulbs")
        ,(bulbs-recycling-process))
       (:div
        ((:class "recycling-batteries-process"))
        (:h2 "Batteries")
        ,(batteries-recycling-process))
       )
      )
     (:div
      ((:class "benefits-incentives-recycling"))
      (:h2 "Benefits of Recycling and Incentives to Recycle")
      (:ol
       (:div
        ((:class "benefits-recycling-1"))
        (:li "Recycling conserves natural resources by reducing the
       dependency on raw resources to create items such as helping
       save forests by recycling paper."))
       (:div
        ((:class "benefits-recycling-2"))
        (:li "Recycling cuts climate-changing carbon emissions since
       recycling uses less energy to make new products as well as
       keeping potentially methane-releasing waste out of landfill
       sites."))
       (:div
        ((:class "benefits-recycling-3"))
        (:li "Recycling protects ecosystems and wildlife by reducing
       the need to grow, harvest or extract new raw materials from
       the Earth."))
       (:div
        ((:class "benefits-recycling-4"))
        (:li "You can make money from recycling (Depending on your
        state), for instance in California you can earn 5 cents per
        aluminum can and even make 10 cents per bottle or can in
        Michigan when turning in the recyclable items to various
        recycling centers."))
       (:div
        ((:class "benefits-recycling-5"))
        (:li "Recycling reduces incineration which generates carbon
       emissions, which contribute to climate change, as well as
       potential air pollution problems."))
       (:div
        ((:class "benefits-recycling-6"))
        (:li "Recycling reduces landfill waste which already releases
       greenhouse gases such as methane into the atmosphere and also
       pollutes soil and water by leaching noxious and toxic liquids
       over time."))
       (:div
        ((:class "benefits-recycling-7"))
        (:li "Recycling has already created over 1.1 million jobs, $236
       billion in gross annual sales, and $37 billion in annual
       payroll."))
       (:div
        ((:class "benefits-recycling-8"))
        (:li "Recycling saves energy since making new products from
       recycled material requires less energy than making them from
       raw materials, for instance producing new aluminium from
       old (including recycled cans and foil) uses 95% less energy
       than making it from scratch."))
       ))
     (:div
      ((:class "info-resources"))
      (:h2 "Sources")
      (:ul
       (:li
        (:a
         ((:href "https://news.wttw.com/2017/06/26/where-does-chicago-s-garbage-go"))
         "WTTW News - 'Where Does Chicago's Garbage Go?' by Elizabeth Brackett"))
       (:li
        (:a
         ((:href "https://projects.bettergov.org/2018/recycling-chicago/"))
         "Better Government Association - 'Recycling in Chicago' by Madison Hopkins"))
       (:li
        (:a
         ((:href "https://www.nbcchicago.com/investigations/chicago-recycling-not-being-recycled-497049481.html"))
         "NBC Chicago - 'A Lot of Chicago Recycling Isn’t Getting Recycled: Report'"))
       (:li
        (:a
         ((:href "https://news.wttw.com/2018/11/19/study-chicago-not-only-city-illinois-struggling-boost-recycling-rate"))
         "WTTW News - 'Study: Chicago Not Only City in Illinois
         Struggling to Boost Recycling Rate' by Alex Ruppenthal"))
       (:li
        (:a
         ((:href "https://news.wttw.com/2017/06/27/chicago-recycling-numbers"))
         "WTTW News - 'Chicago Recycling, By the Numbers' by Alex Ruppenthal"))
       (:li
        (:a
         ((:href "https://depauliaonline.com/37248/news/chicago-ranked-worst-major-american-city-for-recycling/"))
         "The DePaulia - 'Chicago ranked worst major American city for
         recycling' by Ella Lee"))
       (:li
        (:a
         ((:href "https://friendsoftheearth.uk/natural-resources/9-benefits-recycling"))
         "Friends of the Earth - '9 benefits of Recycling'"))
       (:li
        (:a
         ((:href "https://nems.nih.gov/environmental-programs/Pages/Benefits-of-Recycling.aspx"))
         "National Institute of Health - 'Benefits of Recycling'"))))
     )
   )
  )
